### ISSUE TITLE
Question: dans les listes "d", pas besoin d'espace comme pour les listes EFF?

### ISSUE THREAD

**Issue by jeromecc** [mbelivo/diceware-wordlists-fr#1]
Bonjour!

Les listes faites pour le lancement de dés ont bien été générées pour 1 utilisation sans espace?
(Je cite l'article de l'EFF: "Diceware passwords need spaces to be correctly decoded, e.g. in and put are in the list as well as input.")
Merci.

**Comment by mbelivo** [comment]
Bonjour,

Non, cette propriété n'a pas été prise en compte pour générer ces listes, j'ai du l'oubliée en cours de route. Elle est vrai de fait pour la liste 4d.txt car les mots font tous entre 3 et 5 lettres, elle est à vérifier pour les autres, probablement fausse malheureusement, je vais voir ça.

**Comment by mbelivo** [comment]
Pour info, après une vérification rapide,

la liste 4d possède cette propriété, les liste 4d_2 n'ont pas de combinaison de 2 mots et ont peut-être cette propriété, les listes 5d actuelles n'ont clairement *pas* cette propriété.
